# Generated by Django 2.1.5 on 2019-09-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190921_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='这里是标题', max_length=50),
        ),
    ]
