# Generated by Django 2.1.5 on 2019-09-24 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='产品标题', max_length=50)),
                ('intro', models.TextField(default='产品简介')),
                ('product_url', models.URLField()),
                ('product_icon', models.ImageField(upload_to='images/')),
                ('product_image', models.ImageField(upload_to='images/')),
                ('votes', models.IntegerField(default=1)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
