# Generated by Django 2.1.5 on 2019-09-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
