# Generated by Django 2.1.5 on 2019-09-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creat_tiem',
            field=models.DateField(),
        ),
    ]
