# Generated by Django 2.1.5 on 2019-09-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190921_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creat_tiem',
            field=models.DateTimeField(),
        ),
    ]
