# Generated by Django 2.1.5 on 2019-09-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190921_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='creat_time',
            new_name='creat_tiem',
        ),
    ]
