# Generated by Django 2.1.5 on 2019-09-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190922_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='creat_tiem',
            new_name='creat_time',
        ),
    ]
